### ISSUE TITLE
Unable to  initialize sdk

### ISSUE THREAD

**Issue by ranvirgorai** [freshdesk/hotline-phonegap#2] opened 2016-06-01 10:40 UTC
window.Hotline.init(), not working
on calling any method showing, sdk not initialize.

**Comment by vaibhavn1** [comment] 2016-06-02 11:49
Try calling like this

window.Hotline.init({
            appId       : "appid",
            appKey      : "appkey",
            domain      : "app.hotline.io"
        });

**Comment by ranvirgorai** [comment] 2016-06-02 13:46
Still Not Working... I tried this method... Showing same error... if us did successfully plz share code snapshot of controller.js and app.js

**Comment by rsquare2014** [comment] 2016-06-03 15:15
@ranvirjsr  We have a fix for this issue out in v0.4.1 Please let me know if it still persists.

**Comment by rsquare2014** [comment] 2016-06-06 10:47
closing this, please feel free to re-open if the issue is not resolved.

**Closed as completed by rsquare2014** 2016-06-06 10:47 UTC

**Comment by mj6uc** [comment] 2017-06-29 05:38
This is still an issue - ionic 3 app 
* installed plugin
no way to init the SDK...
